In [ ]:
import numpy as np


D = np.array([
    [0.5, 0.5, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
], dtype=float).T


epsilon = 0.05
n = D.shape[0]
D_ext = np.zeros((n + 1, n + 1))

D_ext[:n, :n] = D * (1 - epsilon)
D_ext[n, :] = epsilon
D_ext[n, n] = 1


identity = np.identity(n + 1)
D_no_dial = np.copy(D_ext)
diag = np.diag(D_ext)
D_no_dial[np.diag_indices(n + 1)] -= diag

print(D_ext)
print(np.sum(D_ext, 0))

power = np.linalg.inv(identity - D_no_dial) @ np.ones(n + 1)
power = power * diag

print(power)
print(np.sum(power))
ret_power = np.copy(power[:-1])
ret_power += power[-1] / n
ret_power

[[0.495 0.    0.    0.    0.   ]
 [0.495 0.99  0.    0.    0.   ]
 [0.    0.    0.99  0.    0.   ]
 [0.    0.    0.    0.99  0.   ]
 [0.01  0.01  0.01  0.01  1.   ]]
[1. 1. 1. 1. 1.]
[0.495   1.48005 0.99    0.99    1.04495]
5.0


array([0.7562375, 1.7412875, 1.2512375, 1.2512375])